In [2]:
import pandas as pd

In [22]:
import pandas as pd

# Read the CSV file
df = pd.read_csv(r"C:\Users\RAHUL N MURTHY\Downloads\weather.csv", parse_dates=['Date'])

# Print the first few rows
print(df)

         Date       City  Temperature  Humidity  WindSpeed  Precipitation  \
0  2024-01-01  Bangalore         22.5      65.0        8.2            0.0
1  2024-01-01     Mumbai         28.1      78.0       12.5            0.0
2  2024-01-01      Delhi         12.3      82.0        5.1            0.0
3  2024-01-01    Chennai         26.8      75.0       10.3            0.0
4  2024-01-01    Kolkata         18.5      70.0        7.8            0.0
5  2024-01-02  Bangalore         23.1      62.0        9.0            0.0
6  2024-01-02     Mumbai         28.5      80.0       11.8            2.3
7  2024-01-02      Delhi         11.8      85.0        4.5            0.0
8  2024-01-02    Chennai         27.2      73.0       11.1            0.0
9  2024-01-02    Kolkata         19.0      68.0        8.5            0.0
10 2024-01-03  Bangalore         21.8      68.0        7.5            1.2
11 2024-01-03     Mumbai         29.0      82.0       13.2            5.6
12 2024-01-03      Delhi         13.5      80.0        6.0            0.0
13 2024-01-03    Chennai         26.5      77.0        9.8            0.5
14 2024-01-03    Kolkata         18.2      72.0        7.2            0.0
15 2024-01-04  Bangalore         22.0      70.0        8.0            0.8
16 2024-01-04     Mumbai         27.8      79.0       12.0            0.0
17 2024-01-04      Delhi         14.1      75.0        5.5            0.0
18 2024-01-04    Chennai         27.5      74.0       10.5            0.0
19 2024-01-04    Kolkata         19.5      65.0        8.0            0.0
20 2024-01-05  Bangalore         23.5      60.0        8.8            0.0
21 2024-01-05     Mumbai         28.3      77.0       11.5            0.0
22 2024-01-05      Delhi         15.0      72.0        6.2            0.0
23 2024-01-05    Chennai         28.0      72.0       11.0            0.0
24 2024-01-05    Kolkata         20.1      63.0        8.8            0.0
25 2024-01-06  Bangalore         24.0      58.0        9.2            0.0
26 2024-01-06     Mumbai         29.2      75.0       12.8            0.0
27 2024-01-06      Delhi         15.8      70.0        NaN            0.0
28 2024-01-06    Chennai         28.5      71.0       11.3            0.0
29 2024-01-06    Kolkata         20.8      61.0        9.0            0.0
30 2024-01-07  Bangalore         22.8      64.0        8.5            0.5
31 2024-01-07     Mumbai         28.8      78.0       12.2            1.1
32 2024-01-07      Delhi         14.5      76.0        5.8            0.0
33 2024-01-07    Chennai         27.8       NaN       10.8            0.0
34 2024-01-07    Kolkata         19.8      67.0        8.3            0.0
35 2024-01-08  Bangalore         23.2      61.0        9.1            0.0
36 2024-01-08     Mumbai         29.5      73.0       13.0            0.0
37 2024-01-08      Delhi         16.2      68.0        6.5            0.0
38 2024-01-08    Chennai         28.2      70.0       11.2            0.0
39 2024-01-08    Kolkata         21.0      60.0        9.2            0.0
40 2024-01-09  Bangalore         21.5      72.0        7.8            3.5
41 2024-01-09     Mumbai         28.0      81.0       11.8            4.2
42 2024-01-09      Delhi         13.8      83.0        5.2            0.0
43 2024-01-09    Chennai         26.2      76.0       10.0            2.8
44 2024-01-09    Kolkata         18.8      71.0        7.5            0.0
45 2024-01-10  Bangalore         22.5      66.0        8.4            0.0
46 2024-01-10     Mumbai         28.5      76.0       12.1            0.0
47 2024-01-10      Delhi         14.8      73.0        5.9            0.0
48 2024-01-10    Chennai         27.5      73.0       10.7            0.0
49 2024-01-10    Kolkata         19.5      65.0        8.4            0.0

   Condition
0      Sunny
1     Cloudy
2      Foggy
3      Sunny
4     Cloudy
5      Sunny
6      Rainy
7      Foggy
8      Sunny
9      Sunny
10     Rainy
11     Rainy
12    Cloudy
13    Cloudy
14    Cloudy
15    Cloudy
16    Cloudy
17     Sunny
18     Sunny
19     Sunny
20     Sunny
21     Sunny
22     Sunny
23     Sunny
24     Sunny
25     Sunny
26     Sunny
27     Sunny
28     Sunny
29     Sunny
30    Cloudy
31     Rainy
32     Foggy
33     Sunny
34    Cloudy
35     Sunny
36     Sunny
37     Sunny
38     Sunny
39     Sunny
40     Rainy
41     Rainy
42     Foggy
43     Rainy
44    Cloudy
45    Cloudy
46     Sunny
47     Sunny
48     Sunny
49     Sunny

In [23]:
print(df.shape)

(50, 7)

In [31]:
rows , columns = df.shape 
rows

columns

7

In [32]:
columns

7

In [33]:
df.head(10)

,Date,City,Temperature,Humidity,WindSpeed,Precipitation,Condition
0,2024-01-01,Bangalore,22.5,65.0,8.2,0.0,Sunny
1,2024-01-01,Mumbai,28.1,78.0,12.5,0.0,Cloudy
2,2024-01-01,Delhi,12.3,82.0,5.1,0.0,Foggy
3,2024-01-01,Chennai,26.8,75.0,10.3,0.0,Sunny
4,2024-01-01,Kolkata,18.5,70.0,7.8,0.0,Cloudy
5,2024-01-02,Bangalore,23.1,62.0,9.0,0.0,Sunny
6,2024-01-02,Mumbai,28.5,80.0,11.8,2.3,Rainy
7,2024-01-02,Delhi,11.8,85.0,4.5,0.0,Foggy
8,2024-01-02,Chennai,27.2,73.0,11.1,0.0,Sunny
9,2024-01-02,Kolkata,19.0,68.0,8.5,0.0,Sunny

In [34]:
df.tail(10)

,Date,City,Temperature,Humidity,WindSpeed,Precipitation,Condition
40,2024-01-09,Bangalore,21.5,72.0,7.8,3.5,Rainy
41,2024-01-09,Mumbai,28.0,81.0,11.8,4.2,Rainy
42,2024-01-09,Delhi,13.8,83.0,5.2,0.0,Foggy
43,2024-01-09,Chennai,26.2,76.0,10.0,2.8,Rainy
44,2024-01-09,Kolkata,18.8,71.0,7.5,0.0,Cloudy
45,2024-01-10,Bangalore,22.5,66.0,8.4,0.0,Cloudy
46,2024-01-10,Mumbai,28.5,76.0,12.1,0.0,Sunny
47,2024-01-10,Delhi,14.8,73.0,5.9,0.0,Sunny
48,2024-01-10,Chennai,27.5,73.0,10.7,0.0,Sunny
49,2024-01-10,Kolkata,19.5,65.0,8.4,0.0,Sunny

In [36]:
df[2:10:2]

,Date,City,Temperature,Humidity,WindSpeed,Precipitation,Condition
2,2024-01-01,Delhi,12.3,82.0,5.1,0.0,Foggy
4,2024-01-01,Kolkata,18.5,70.0,7.8,0.0,Cloudy
6,2024-01-02,Mumbai,28.5,80.0,11.8,2.3,Rainy
8,2024-01-02,Chennai,27.2,73.0,11.1,0.0,Sunny

In [37]:
df.columns

Index(['Date', 'City', 'Temperature', 'Humidity', 'WindSpeed', 'Precipitation',
       'Condition'],
      dtype='str')

In [41]:
df.Date

0    2024-01-01
1    2024-01-01
2    2024-01-01
3    2024-01-01
4    2024-01-01
5    2024-01-02
6    2024-01-02
7    2024-01-02
8    2024-01-02
9    2024-01-02
10   2024-01-03
11   2024-01-03
12   2024-01-03
13   2024-01-03
14   2024-01-03
15   2024-01-04
16   2024-01-04
17   2024-01-04
18   2024-01-04
19   2024-01-04
20   2024-01-05
21   2024-01-05
22   2024-01-05
23   2024-01-05
24   2024-01-05
25   2024-01-06
26   2024-01-06
27   2024-01-06
28   2024-01-06
29   2024-01-06
30   2024-01-07
31   2024-01-07
32   2024-01-07
33   2024-01-07
34   2024-01-07
35   2024-01-08
36   2024-01-08
37   2024-01-08
38   2024-01-08
39   2024-01-08
40   2024-01-09
41   2024-01-09
42   2024-01-09
43   2024-01-09
44   2024-01-09
45   2024-01-10
46   2024-01-10
47   2024-01-10
48   2024-01-10
49   2024-01-10
Name: Date, dtype: datetime64[us]

In [42]:
df[['Date', 'City']]

         Date       City
0  2024-01-01  Bangalore
1  2024-01-01     Mumbai
2  2024-01-01      Delhi
3  2024-01-01    Chennai
4  2024-01-01    Kolkata
5  2024-01-02  Bangalore
6  2024-01-02     Mumbai
7  2024-01-02      Delhi
8  2024-01-02    Chennai
9  2024-01-02    Kolkata
10 2024-01-03  Bangalore
11 2024-01-03     Mumbai
12 2024-01-03      Delhi
13 2024-01-03    Chennai
14 2024-01-03    Kolkata
15 2024-01-04  Bangalore
16 2024-01-04     Mumbai
17 2024-01-04      Delhi
18 2024-01-04    Chennai
19 2024-01-04    Kolkata
20 2024-01-05  Bangalore
21 2024-01-05     Mumbai
22 2024-01-05      Delhi
23 2024-01-05    Chennai
24 2024-01-05    Kolkata
25 2024-01-06  Bangalore
26 2024-01-06     Mumbai
27 2024-01-06      Delhi
28 2024-01-06    Chennai
29 2024-01-06    Kolkata
30 2024-01-07  Bangalore
31 2024-01-07     Mumbai
32 2024-01-07      Delhi
33 2024-01-07    Chennai
34 2024-01-07    Kolkata
35 2024-01-08  Bangalore
36 2024-01-08     Mumbai
37 2024-01-08      Delhi
38 2024-01-08    Chennai
39 2024-01-08    Kolkata
40 2024-01-09  Bangalore
41 2024-01-09     Mumbai
42 2024-01-09      Delhi
43 2024-01-09    Chennai
44 2024-01-09    Kolkata
45 2024-01-10  Bangalore
46 2024-01-10     Mumbai
47 2024-01-10      Delhi
48 2024-01-10    Chennai
49 2024-01-10    Kolkata

In [46]:
df[df.WindSpeed>= 11.0]

,Date,City,Temperature,Humidity,WindSpeed,Precipitation,Condition
1,2024-01-01,Mumbai,28.1,78.0,12.5,0.0,Cloudy
6,2024-01-02,Mumbai,28.5,80.0,11.8,2.3,Rainy
8,2024-01-02,Chennai,27.2,73.0,11.1,0.0,Sunny
11,2024-01-03,Mumbai,29.0,82.0,13.2,5.6,Rainy
16,2024-01-04,Mumbai,27.8,79.0,12.0,0.0,Cloudy
21,2024-01-05,Mumbai,28.3,77.0,11.5,0.0,Sunny
23,2024-01-05,Chennai,28.0,72.0,11.0,0.0,Sunny
26,2024-01-06,Mumbai,29.2,75.0,12.8,0.0,Sunny
28,2024-01-06,Chennai,28.5,71.0,11.3,0.0,Sunny
31,2024-01-07,Mumbai,28.8,78.0,12.2,1.1,Rainy
36,2024-01-08,Mumbai,29.5,73.0,13.0,0.0,Sunny
38,2024-01-08,Chennai,28.2,70.0,11.2,0.0,Sunny
41,2024-01-09,Mumbai,28.0,81.0,11.8,4.2,Rainy
46,2024-01-10,Mumbai,28.5,76.0,12.1,0.0,Sunny

In [4]:
import pandas as pd 
bf = pd.read_excel(r"C:\Users\RAHUL N MURTHY\Downloads\ecommerce_practice.xlsx",
                   sheet_name="Orders",
                   parse_dates=['OrderDate'])

In [5]:
print (bf.head())

    OrderID CustomerID ProductID  OrderDate       City     Category  Quantity  \
0  ORD00001    CUST039   PROD015 2024-01-01     Mumbai         Toys         3
1  ORD00002    CUST029   PROD027 2024-01-02  Hyderabad  Electronics         4
2  ORD00003    CUST015   PROD022 2024-01-04  Hyderabad       Beauty         1
3  ORD00004    CUST043   PROD024 2024-01-06  Bangalore         Toys         5
4  ORD00005    CUST008   PROD009 2024-01-08  Hyderabad    Furniture         5

   UnitPrice  Discount  TotalAmount  PaymentMode     Status  Rating
0    5334.57      0.20     12802.97   Debit Card  Delivered     5.0
1   45146.13      0.05    171555.29  Net Banking  Cancelled     3.0
2   25360.57      0.15     21556.48  Credit Card  Delivered     3.0
3   41356.58      0.05    196443.76  Credit Card  Delivered     5.0
4   16137.47      0.20     64549.88  Net Banking    Pending     5.0

In [10]:
import os 
import pandas as pd 
os.chdir(r"C:\Users\RAHUL N MURTHY\Downloads")

In [12]:
bf = pd.read_excel("ecommerce_practice.xlsx")
print(bf.head())

    OrderID CustomerID ProductID   OrderDate       City     Category  \
0  ORD00001    CUST039   PROD015  2024-01-01     Mumbai         Toys
1  ORD00002    CUST029   PROD027  2024-01-02  Hyderabad  Electronics
2  ORD00003    CUST015   PROD022  2024-01-04  Hyderabad       Beauty
3  ORD00004    CUST043   PROD024  2024-01-06  Bangalore         Toys
4  ORD00005    CUST008   PROD009  2024-01-08  Hyderabad    Furniture

   Quantity  UnitPrice  Discount  TotalAmount  PaymentMode     Status  Rating
0         3    5334.57      0.20     12802.97   Debit Card  Delivered     5.0
1         4   45146.13      0.05    171555.29  Net Banking  Cancelled     3.0
2         1   25360.57      0.15     21556.48  Credit Card  Delivered     3.0
3         5   41356.58      0.05    196443.76  Credit Card  Delivered     5.0
4         5   16137.47      0.20     64549.88  Net Banking    Pending     5.0

In [19]:
df = pd.read_excel("ecommerce_practice.xlsx", sheet_name="Orders")

print(df)              # print entire DataFrame
print(df.head())       # first 5 rows (default)
print(df.head(10))     # first 10 rows
print(df.tail())       # last 5 rows
print(df.tail(10))     # last 10 rows

      OrderID CustomerID ProductID   OrderDate       City        Category  \
0    ORD00001    CUST039   PROD015  2024-01-01     Mumbai            Toys
1    ORD00002    CUST029   PROD027  2024-01-02  Hyderabad     Electronics
2    ORD00003    CUST015   PROD022  2024-01-04  Hyderabad          Beauty
3    ORD00004    CUST043   PROD024  2024-01-06  Bangalore            Toys
4    ORD00005    CUST008   PROD009  2024-01-08  Hyderabad       Furniture
..        ...        ...       ...         ...        ...             ...
195  ORD00196    CUST037   PROD030  2024-12-23       Pune       Furniture
196  ORD00197    CUST033   PROD029  2024-12-25  Bangalore  Home & Kitchen
197  ORD00198    CUST042   PROD014  2024-12-27      Delhi            Toys
198  ORD00199    CUST044   PROD021  2024-12-29  Bangalore          Beauty
199  ORD00200    CUST024   PROD006  2024-12-31      Delhi       Furniture

     Quantity  UnitPrice  Discount  TotalAmount  PaymentMode     Status  \
0           3    5334.57      0.20     12802.97   Debit Card  Delivered
1           4   45146.13      0.05    171555.29  Net Banking  Cancelled
2           1   25360.57      0.15     21556.48  Credit Card  Delivered
3           5   41356.58      0.05    196443.76  Credit Card  Delivered
4           5   16137.47      0.20     64549.88  Net Banking    Pending
..        ...        ...       ...          ...          ...        ...
195         4   23802.29      0.00     95209.16  Credit Card    Shipped
196         1   33443.38      0.20     26754.70          UPI  Delivered
197         5    8780.53      0.25     32926.99          UPI    Shipped
198         1    9774.99      0.15      8308.74          UPI    Shipped
199         3    2234.26      0.25      5027.09  Net Banking    Shipped

     Rating
0       5.0
1       3.0
2       3.0
3       5.0
4       5.0
..      ...
195     4.0
196     4.0
197     5.0
198     5.0
199     4.0

[200 rows x 13 columns]
    OrderID CustomerID ProductID   OrderDate       City     Category  \
0  ORD00001    CUST039   PROD015  2024-01-01     Mumbai         Toys
1  ORD00002    CUST029   PROD027  2024-01-02  Hyderabad  Electronics
2  ORD00003    CUST015   PROD022  2024-01-04  Hyderabad       Beauty
3  ORD00004    CUST043   PROD024  2024-01-06  Bangalore         Toys
4  ORD00005    CUST008   PROD009  2024-01-08  Hyderabad    Furniture

   Quantity  UnitPrice  Discount  TotalAmount  PaymentMode     Status  Rating
0         3    5334.57      0.20     12802.97   Debit Card  Delivered     5.0
1         4   45146.13      0.05    171555.29  Net Banking  Cancelled     3.0
2         1   25360.57      0.15     21556.48  Credit Card  Delivered     3.0
3         5   41356.58      0.05    196443.76  Credit Card  Delivered     5.0
4         5   16137.47      0.20     64549.88  Net Banking    Pending     5.0
    OrderID CustomerID ProductID   OrderDate       City        Category  \
0  ORD00001    CUST039   PROD015  2024-01-01     Mumbai            Toys
1  ORD00002    CUST029   PROD027  2024-01-02  Hyderabad     Electronics
2  ORD00003    CUST015   PROD022  2024-01-04  Hyderabad          Beauty
3  ORD00004    CUST043   PROD024  2024-01-06  Bangalore            Toys
4  ORD00005    CUST008   PROD009  2024-01-08  Hyderabad       Furniture
5  ORD00006    CUST021   PROD020  2024-01-10    Chennai           Books
6  ORD00007    CUST039   PROD017  2024-01-12      Delhi  Home & Kitchen
7  ORD00008    CUST019   PROD030  2024-01-13      Delhi  Home & Kitchen
8  ORD00009    CUST023   PROD017  2024-01-15    Kolkata          Sports
9  ORD00010    CUST011   PROD026  2024-01-17    Kolkata        Clothing

   Quantity  UnitPrice  Discount  TotalAmount  PaymentMode     Status  Rating
0         3    5334.57      0.20     12802.97   Debit Card  Delivered     5.0
1         4   45146.13      0.05    171555.29  Net Banking  Cancelled     3.0
2         1   25360.57      0.15     21556.48  Credit Card  Delivered     3.0
3         5   41356.58      0.05    196443.76  Credit Card  Delivered     5.0
4         5   16137.47      0.20     64549.88  Net Banking    Pending     5.0
5         1   44796.06      0.25     33597.04          COD  Delivered     NaN
6         5   19581.24      0.20     78324.96  Net Banking    Shipped     4.0
7         3     738.72      0.25      1662.12          COD  Cancelled     5.0
8         4   45287.02      0.00    181148.08  Net Banking  Delivered     4.0
9         1    4745.08      0.20      3796.06  Net Banking    Shipped     5.0
      OrderID CustomerID ProductID   OrderDate       City        Category  \
195  ORD00196    CUST037   PROD030  2024-12-23       Pune       Furniture
196  ORD00197    CUST033   PROD029  2024-12-25  Bangalore  Home & Kitchen
197  ORD00198    CUST042   PROD014  2024-12-27      Delhi            Toys
198  ORD00199    CUST044   PROD021  2024-12-29  Bangalore          Beauty
199  ORD00200    CUST024   PROD006  2024-12-31      Delhi       Furniture

     Quantity  UnitPrice  Discount  TotalAmount  PaymentMode     Status  \
195         4   23802.29      0.00     95209.16  Credit Card    Shipped
196         1   33443.38      0.20     26754.70          UPI  Delivered
197         5    8780.53      0.25     32926.99          UPI    Shipped
198         1    9774.99      0.15      8308.74          UPI    Shipped
199         3    2234.26      0.25      5027.09  Net Banking    Shipped

     Rating
195     4.0
196     4.0
197     5.0
198     5.0
199     4.0
      OrderID CustomerID ProductID   OrderDate       City        Category  \
190  ORD00191    CUST039   PROD003  2024-12-14    Kolkata     Electronics
191  ORD00192    CUST006   PROD017  2024-12-16      Delhi          Sports
192  ORD00193    CUST008   PROD017  2024-12-18       Pune           Books
193  ORD00194    CUST027   PROD012  2024-12-19  Hyderabad           Books
194  ORD00195    CUST009   PROD028  2024-12-21    Chennai        Clothing
195  ORD00196    CUST037   PROD030  2024-12-23       Pune       Furniture
196  ORD00197    CUST033   PROD029  2024-12-25  Bangalore  Home & Kitchen
197  ORD00198    CUST042   PROD014  2024-12-27      Delhi            Toys
198  ORD00199    CUST044   PROD021  2024-12-29  Bangalore          Beauty
199  ORD00200    CUST024   PROD006  2024-12-31      Delhi       Furniture

     Quantity  UnitPrice  Discount  TotalAmount  PaymentMode     Status  \
190         3    7112.59      0.00     21337.77          UPI   Returned
191         4   32114.56      0.25     96343.68  Credit Card  Delivered
192         2    9256.63      0.15     15736.27          NaN   Returned
193         1   17413.23      0.20     13930.58          COD  Delivered
194         5   44859.06      0.10    201865.77          UPI  Delivered
195         4   23802.29      0.00     95209.16  Credit Card    Shipped
196         1   33443.38      0.20     26754.70          UPI  Delivered
197         5    8780.53      0.25     32926.99          UPI    Shipped
198         1    9774.99      0.15      8308.74          UPI    Shipped
199         3    2234.26      0.25      5027.09  Net Banking    Shipped

     Rating
190     2.0
191     4.0
192     NaN
193     4.0
194     NaN
195     4.0
196     4.0
197     5.0
198     5.0
199     4.0

In [21]:
df = pd.read_excel("ecommerce_practice.xlsx", sheet_name=0)

print(df)              # print entire DataFrame
print(df.head())       # first 5 rows (default)
print(df.head(10))     # first 10 rows
print(df.tail())       # last 5 rows
print(df.tail(10))     # last 10 rows

      OrderID CustomerID ProductID   OrderDate       City        Category  \
0    ORD00001    CUST039   PROD015  2024-01-01     Mumbai            Toys
1    ORD00002    CUST029   PROD027  2024-01-02  Hyderabad     Electronics
2    ORD00003    CUST015   PROD022  2024-01-04  Hyderabad          Beauty
3    ORD00004    CUST043   PROD024  2024-01-06  Bangalore            Toys
4    ORD00005    CUST008   PROD009  2024-01-08  Hyderabad       Furniture
..        ...        ...       ...         ...        ...             ...
195  ORD00196    CUST037   PROD030  2024-12-23       Pune       Furniture
196  ORD00197    CUST033   PROD029  2024-12-25  Bangalore  Home & Kitchen
197  ORD00198    CUST042   PROD014  2024-12-27      Delhi            Toys
198  ORD00199    CUST044   PROD021  2024-12-29  Bangalore          Beauty
199  ORD00200    CUST024   PROD006  2024-12-31      Delhi       Furniture

     Quantity  UnitPrice  Discount  TotalAmount  PaymentMode     Status  \
0           3    5334.57      0.20     12802.97   Debit Card  Delivered
1           4   45146.13      0.05    171555.29  Net Banking  Cancelled
2           1   25360.57      0.15     21556.48  Credit Card  Delivered
3           5   41356.58      0.05    196443.76  Credit Card  Delivered
4           5   16137.47      0.20     64549.88  Net Banking    Pending
..        ...        ...       ...          ...          ...        ...
195         4   23802.29      0.00     95209.16  Credit Card    Shipped
196         1   33443.38      0.20     26754.70          UPI  Delivered
197         5    8780.53      0.25     32926.99          UPI    Shipped
198         1    9774.99      0.15      8308.74          UPI    Shipped
199         3    2234.26      0.25      5027.09  Net Banking    Shipped

     Rating
0       5.0
1       3.0
2       3.0
3       5.0
4       5.0
..      ...
195     4.0
196     4.0
197     5.0
198     5.0
199     4.0

[200 rows x 13 columns]
    OrderID CustomerID ProductID   OrderDate       City     Category  \
0  ORD00001    CUST039   PROD015  2024-01-01     Mumbai         Toys
1  ORD00002    CUST029   PROD027  2024-01-02  Hyderabad  Electronics
2  ORD00003    CUST015   PROD022  2024-01-04  Hyderabad       Beauty
3  ORD00004    CUST043   PROD024  2024-01-06  Bangalore         Toys
4  ORD00005    CUST008   PROD009  2024-01-08  Hyderabad    Furniture

   Quantity  UnitPrice  Discount  TotalAmount  PaymentMode     Status  Rating
0         3    5334.57      0.20     12802.97   Debit Card  Delivered     5.0
1         4   45146.13      0.05    171555.29  Net Banking  Cancelled     3.0
2         1   25360.57      0.15     21556.48  Credit Card  Delivered     3.0
3         5   41356.58      0.05    196443.76  Credit Card  Delivered     5.0
4         5   16137.47      0.20     64549.88  Net Banking    Pending     5.0
    OrderID CustomerID ProductID   OrderDate       City        Category  \
0  ORD00001    CUST039   PROD015  2024-01-01     Mumbai            Toys
1  ORD00002    CUST029   PROD027  2024-01-02  Hyderabad     Electronics
2  ORD00003    CUST015   PROD022  2024-01-04  Hyderabad          Beauty
3  ORD00004    CUST043   PROD024  2024-01-06  Bangalore            Toys
4  ORD00005    CUST008   PROD009  2024-01-08  Hyderabad       Furniture
5  ORD00006    CUST021   PROD020  2024-01-10    Chennai           Books
6  ORD00007    CUST039   PROD017  2024-01-12      Delhi  Home & Kitchen
7  ORD00008    CUST019   PROD030  2024-01-13      Delhi  Home & Kitchen
8  ORD00009    CUST023   PROD017  2024-01-15    Kolkata          Sports
9  ORD00010    CUST011   PROD026  2024-01-17    Kolkata        Clothing

   Quantity  UnitPrice  Discount  TotalAmount  PaymentMode     Status  Rating
0         3    5334.57      0.20     12802.97   Debit Card  Delivered     5.0
1         4   45146.13      0.05    171555.29  Net Banking  Cancelled     3.0
2         1   25360.57      0.15     21556.48  Credit Card  Delivered     3.0
3         5   41356.58      0.05    196443.76  Credit Card  Delivered     5.0
4         5   16137.47      0.20     64549.88  Net Banking    Pending     5.0
5         1   44796.06      0.25     33597.04          COD  Delivered     NaN
6         5   19581.24      0.20     78324.96  Net Banking    Shipped     4.0
7         3     738.72      0.25      1662.12          COD  Cancelled     5.0
8         4   45287.02      0.00    181148.08  Net Banking  Delivered     4.0
9         1    4745.08      0.20      3796.06  Net Banking    Shipped     5.0
      OrderID CustomerID ProductID   OrderDate       City        Category  \
195  ORD00196    CUST037   PROD030  2024-12-23       Pune       Furniture
196  ORD00197    CUST033   PROD029  2024-12-25  Bangalore  Home & Kitchen
197  ORD00198    CUST042   PROD014  2024-12-27      Delhi            Toys
198  ORD00199    CUST044   PROD021  2024-12-29  Bangalore          Beauty
199  ORD00200    CUST024   PROD006  2024-12-31      Delhi       Furniture

     Quantity  UnitPrice  Discount  TotalAmount  PaymentMode     Status  \
195         4   23802.29      0.00     95209.16  Credit Card    Shipped
196         1   33443.38      0.20     26754.70          UPI  Delivered
197         5    8780.53      0.25     32926.99          UPI    Shipped
198         1    9774.99      0.15      8308.74          UPI    Shipped
199         3    2234.26      0.25      5027.09  Net Banking    Shipped

     Rating
195     4.0
196     4.0
197     5.0
198     5.0
199     4.0
      OrderID CustomerID ProductID   OrderDate       City        Category  \
190  ORD00191    CUST039   PROD003  2024-12-14    Kolkata     Electronics
191  ORD00192    CUST006   PROD017  2024-12-16      Delhi          Sports
192  ORD00193    CUST008   PROD017  2024-12-18       Pune           Books
193  ORD00194    CUST027   PROD012  2024-12-19  Hyderabad           Books
194  ORD00195    CUST009   PROD028  2024-12-21    Chennai        Clothing
195  ORD00196    CUST037   PROD030  2024-12-23       Pune       Furniture
196  ORD00197    CUST033   PROD029  2024-12-25  Bangalore  Home & Kitchen
197  ORD00198    CUST042   PROD014  2024-12-27      Delhi            Toys
198  ORD00199    CUST044   PROD021  2024-12-29  Bangalore          Beauty
199  ORD00200    CUST024   PROD006  2024-12-31      Delhi       Furniture

     Quantity  UnitPrice  Discount  TotalAmount  PaymentMode     Status  \
190         3    7112.59      0.00     21337.77          UPI   Returned
191         4   32114.56      0.25     96343.68  Credit Card  Delivered
192         2    9256.63      0.15     15736.27          NaN   Returned
193         1   17413.23      0.20     13930.58          COD  Delivered
194         5   44859.06      0.10    201865.77          UPI  Delivered
195         4   23802.29      0.00     95209.16  Credit Card    Shipped
196         1   33443.38      0.20     26754.70          UPI  Delivered
197         5    8780.53      0.25     32926.99          UPI    Shipped
198         1    9774.99      0.15      8308.74          UPI    Shipped
199         3    2234.26      0.25      5027.09  Net Banking    Shipped

     Rating
190     2.0
191     4.0
192     NaN
193     4.0
194     NaN
195     4.0
196     4.0
197     5.0
198     5.0
199     4.0

In [27]:
all_sheets = pd.read_excel("ecommerce_practice.xlsx",sheet_name= None )
print (all_sheets.keys())
Products= all_sheets["Products"]
print(Products.head())

dict_keys(['Orders', 'Products', 'Customers', 'Summary'])
  ProductID         ProductName     Category    Brand  StockQty  CostPrice  \
0   PROD001           iPhone 15  Electronics    Apple       115    2039.12
1   PROD002  Samsung Galaxy S24  Electronics  Samsung       385   17441.52
2   PROD003          OnePlus 12  Electronics  OnePlus       136   16888.39
3   PROD004        Boat Earbuds  Electronics     Boat        24   16863.74
4   PROD005     Sony Headphones  Electronics     Sony       398   18144.28

   SellingPrice InStock
0      39324.45     Yes
1       6092.14     Yes
2      20612.26     Yes
3      42021.15     Yes
4      19313.88     Yes

In [32]:
bf = pd.read_excel("ecommerce_practice.xlsx", skiprows = 1 )
bf

,ORD00001,CUST039,PROD015,2024-01-01,Mumbai,Toys,3,5334.57,0.2,12802.97,Debit Card,Delivered,5
0,ORD00002,CUST029,PROD027,2024-01-02,Hyderabad,Electronics,4,45146.13,0.05,171555.29,Net Banking,Cancelled,3.0
1,ORD00003,CUST015,PROD022,2024-01-04,Hyderabad,Beauty,1,25360.57,0.15,21556.48,Credit Card,Delivered,3.0
2,ORD00004,CUST043,PROD024,2024-01-06,Bangalore,Toys,5,41356.58,0.05,196443.76,Credit Card,Delivered,5.0
3,ORD00005,CUST008,PROD009,2024-01-08,Hyderabad,Furniture,5,16137.47,0.20,64549.88,Net Banking,Pending,5.0
4,ORD00006,CUST021,PROD020,2024-01-10,Chennai,Books,1,44796.06,0.25,33597.04,COD,Delivered,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
194,ORD00196,CUST037,PROD030,2024-12-23,Pune,Furniture,4,23802.29,0.00,95209.16,Credit Card,Shipped,4.0
195,ORD00197,CUST033,PROD029,2024-12-25,Bangalore,Home & Kitchen,1,33443.38,0.20,26754.70,UPI,Delivered,4.0
196,ORD00198,CUST042,PROD014,2024-12-27,Delhi,Toys,5,8780.53,0.25,32926.99,UPI,Shipped,5.0
197,ORD00199,CUST044,PROD021,2024-12-29,Bangalore,Beauty,1,9774.99,0.15,8308.74,UPI,Shipped,5.0
198,ORD00200,CUST024,PROD006,2024-12-31,Delhi,Furniture,3,2234.26,0.25,5027.09,Net Banking,Shipped,4.0

In [37]:
bf = pd.read_excel("ecommerce_practice.xlsx" , header = None  )
bf

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,OrderID,CustomerID,ProductID,OrderDate,City,Category,Quantity,UnitPrice,Discount,TotalAmount,PaymentMode,Status,Rating
1,ORD00001,CUST039,PROD015,2024-01-01,Mumbai,Toys,3,5334.57,0.2,12802.97,Debit Card,Delivered,5
2,ORD00002,CUST029,PROD027,2024-01-02,Hyderabad,Electronics,4,45146.13,0.05,171555.29,Net Banking,Cancelled,3
3,ORD00003,CUST015,PROD022,2024-01-04,Hyderabad,Beauty,1,25360.57,0.15,21556.48,Credit Card,Delivered,3
4,ORD00004,CUST043,PROD024,2024-01-06,Bangalore,Toys,5,41356.58,0.05,196443.76,Credit Card,Delivered,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
196,ORD00196,CUST037,PROD030,2024-12-23,Pune,Furniture,4,23802.29,0,95209.16,Credit Card,Shipped,4
197,ORD00197,CUST033,PROD029,2024-12-25,Bangalore,Home & Kitchen,1,33443.38,0.2,26754.7,UPI,Delivered,4
198,ORD00198,CUST042,PROD014,2024-12-27,Delhi,Toys,5,8780.53,0.25,32926.99,UPI,Shipped,5
199,ORD00199,CUST044,PROD021,2024-12-29,Bangalore,Beauty,1,9774.99,0.15,8308.74,UPI,Shipped,5
200,ORD00200,CUST024,PROD006,2024-12-31,Delhi,Furniture,3,2234.26,0.25,5027.09,Net Banking,Shipped,4

In [38]:
bf = pd.read_excel("ecommerce_practice.xlsx" , nrows = 3)
bf

,OrderID,CustomerID,ProductID,OrderDate,City,Category,Quantity,UnitPrice,Discount,TotalAmount,PaymentMode,Status,Rating
0,ORD00001,CUST039,PROD015,2024-01-01,Mumbai,Toys,3,5334.57,0.20,12802.97,Debit Card,Delivered,5
1,ORD00002,CUST029,PROD027,2024-01-02,Hyderabad,Electronics,4,45146.13,0.05,171555.29,Net Banking,Cancelled,3
2,ORD00003,CUST015,PROD022,2024-01-04,Hyderabad,Beauty,1,25360.57,0.15,21556.48,Credit Card,Delivered,3

In [41]:
bf = pd.read_excel("ecommerce_practice.xlsx", na_values = { "OrderDate" : [ "not available ", "n.a"],
                                                            "ProductID " : [ "not available ", "n.a", -1 ],
                                                            "Discount" : [ "not available ", "n.a"] })
bf

,OrderID,CustomerID,ProductID,OrderDate,City,Category,Quantity,UnitPrice,Discount,TotalAmount,PaymentMode,Status,Rating
0,ORD00001,CUST039,PROD015,2024-01-01,Mumbai,Toys,3,5334.57,0.20,12802.97,Debit Card,Delivered,5.0
1,ORD00002,CUST029,PROD027,2024-01-02,Hyderabad,Electronics,4,45146.13,0.05,171555.29,Net Banking,Cancelled,3.0
2,ORD00003,CUST015,PROD022,2024-01-04,Hyderabad,Beauty,1,25360.57,0.15,21556.48,Credit Card,Delivered,3.0
3,ORD00004,CUST043,PROD024,2024-01-06,Bangalore,Toys,5,41356.58,0.05,196443.76,Credit Card,Delivered,5.0
4,ORD00005,CUST008,PROD009,2024-01-08,Hyderabad,Furniture,5,16137.47,0.20,64549.88,Net Banking,Pending,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,ORD00196,CUST037,PROD030,2024-12-23,Pune,Furniture,4,23802.29,0.00,95209.16,Credit Card,Shipped,4.0
196,ORD00197,CUST033,PROD029,2024-12-25,Bangalore,Home & Kitchen,1,33443.38,0.20,26754.70,UPI,Delivered,4.0
197,ORD00198,CUST042,PROD014,2024-12-27,Delhi,Toys,5,8780.53,0.25,32926.99,UPI,Shipped,5.0
198,ORD00199,CUST044,PROD021,2024-12-29,Bangalore,Beauty,1,9774.99,0.15,8308.74,UPI,Shipped,5.0
199,ORD00200,CUST024,PROD006,2024-12-31,Delhi,Furniture,3,2234.26,0.25,5027.09,Net Banking,Shipped,4.0

In [46]:
bf.to_excel("new.xlsx" )
bf

,OrderID,CustomerID,ProductID,OrderDate,City,Category,Quantity,UnitPrice,Discount,TotalAmount,PaymentMode,Status,Rating
0,ORD00001,CUST039,PROD015,2024-01-01,Mumbai,Toys,3,5334.57,0.20,12802.97,Debit Card,Delivered,5.0
1,ORD00002,CUST029,PROD027,2024-01-02,Hyderabad,Electronics,4,45146.13,0.05,171555.29,Net Banking,Cancelled,3.0
2,ORD00003,CUST015,PROD022,2024-01-04,Hyderabad,Beauty,1,25360.57,0.15,21556.48,Credit Card,Delivered,3.0
3,ORD00004,CUST043,PROD024,2024-01-06,Bangalore,Toys,5,41356.58,0.05,196443.76,Credit Card,Delivered,5.0
4,ORD00005,CUST008,PROD009,2024-01-08,Hyderabad,Furniture,5,16137.47,0.20,64549.88,Net Banking,Pending,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,ORD00196,CUST037,PROD030,2024-12-23,Pune,Furniture,4,23802.29,0.00,95209.16,Credit Card,Shipped,4.0
196,ORD00197,CUST033,PROD029,2024-12-25,Bangalore,Home & Kitchen,1,33443.38,0.20,26754.70,UPI,Delivered,4.0
197,ORD00198,CUST042,PROD014,2024-12-27,Delhi,Toys,5,8780.53,0.25,32926.99,UPI,Shipped,5.0
198,ORD00199,CUST044,PROD021,2024-12-29,Bangalore,Beauty,1,9774.99,0.15,8308.74,UPI,Shipped,5.0
199,ORD00200,CUST024,PROD006,2024-12-31,Delhi,Furniture,3,2234.26,0.25,5027.09,Net Banking,Shipped,4.0

In [49]:
bf.to_excel("new.xlsx" , index = False )
bf

,OrderID,CustomerID,ProductID,OrderDate,City,Category,Quantity,UnitPrice,Discount,TotalAmount,PaymentMode,Status,Rating
0,ORD00001,CUST039,PROD015,2024-01-01,Mumbai,Toys,3,5334.57,0.20,12802.97,Debit Card,Delivered,5.0
1,ORD00002,CUST029,PROD027,2024-01-02,Hyderabad,Electronics,4,45146.13,0.05,171555.29,Net Banking,Cancelled,3.0
2,ORD00003,CUST015,PROD022,2024-01-04,Hyderabad,Beauty,1,25360.57,0.15,21556.48,Credit Card,Delivered,3.0
3,ORD00004,CUST043,PROD024,2024-01-06,Bangalore,Toys,5,41356.58,0.05,196443.76,Credit Card,Delivered,5.0
4,ORD00005,CUST008,PROD009,2024-01-08,Hyderabad,Furniture,5,16137.47,0.20,64549.88,Net Banking,Pending,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,ORD00196,CUST037,PROD030,2024-12-23,Pune,Furniture,4,23802.29,0.00,95209.16,Credit Card,Shipped,4.0
196,ORD00197,CUST033,PROD029,2024-12-25,Bangalore,Home & Kitchen,1,33443.38,0.20,26754.70,UPI,Delivered,4.0
197,ORD00198,CUST042,PROD014,2024-12-27,Delhi,Toys,5,8780.53,0.25,32926.99,UPI,Shipped,5.0
198,ORD00199,CUST044,PROD021,2024-12-29,Bangalore,Beauty,1,9774.99,0.15,8308.74,UPI,Shipped,5.0
199,ORD00200,CUST024,PROD006,2024-12-31,Delhi,Furniture,3,2234.26,0.25,5027.09,Net Banking,Shipped,4.0

In [53]:
bf.to_excel("new.xlsx", sheet_name = "order ", index = False)

In [54]:
bf.to_excel("new.xlsx", startrow = 1 , startcol = 1 , index = False )
bf

,OrderID,CustomerID,ProductID,OrderDate,City,Category,Quantity,UnitPrice,Discount,TotalAmount,PaymentMode,Status,Rating
0,ORD00001,CUST039,PROD015,2024-01-01,Mumbai,Toys,3,5334.57,0.20,12802.97,Debit Card,Delivered,5.0
1,ORD00002,CUST029,PROD027,2024-01-02,Hyderabad,Electronics,4,45146.13,0.05,171555.29,Net Banking,Cancelled,3.0
2,ORD00003,CUST015,PROD022,2024-01-04,Hyderabad,Beauty,1,25360.57,0.15,21556.48,Credit Card,Delivered,3.0
3,ORD00004,CUST043,PROD024,2024-01-06,Bangalore,Toys,5,41356.58,0.05,196443.76,Credit Card,Delivered,5.0
4,ORD00005,CUST008,PROD009,2024-01-08,Hyderabad,Furniture,5,16137.47,0.20,64549.88,Net Banking,Pending,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,ORD00196,CUST037,PROD030,2024-12-23,Pune,Furniture,4,23802.29,0.00,95209.16,Credit Card,Shipped,4.0
196,ORD00197,CUST033,PROD029,2024-12-25,Bangalore,Home & Kitchen,1,33443.38,0.20,26754.70,UPI,Delivered,4.0
197,ORD00198,CUST042,PROD014,2024-12-27,Delhi,Toys,5,8780.53,0.25,32926.99,UPI,Shipped,5.0
198,ORD00199,CUST044,PROD021,2024-12-29,Bangalore,Beauty,1,9774.99,0.15,8308.74,UPI,Shipped,5.0
199,ORD00200,CUST024,PROD006,2024-12-31,Delhi,Furniture,3,2234.26,0.25,5027.09,Net Banking,Shipped,4.0

In [60]:
bf.to_excel("new.xlsx", header=["order","cudtomer", "product", "date", "city", "cat", " quantity ", "up", " dis" , " ta", "pm", "status ", "rating "   ], index = False)
bf

,OrderID,CustomerID,ProductID,OrderDate,City,Category,Quantity,UnitPrice,Discount,TotalAmount,PaymentMode,Status,Rating
0,ORD00001,CUST039,PROD015,2024-01-01,Mumbai,Toys,3,5334.57,0.20,12802.97,Debit Card,Delivered,5.0
1,ORD00002,CUST029,PROD027,2024-01-02,Hyderabad,Electronics,4,45146.13,0.05,171555.29,Net Banking,Cancelled,3.0
2,ORD00003,CUST015,PROD022,2024-01-04,Hyderabad,Beauty,1,25360.57,0.15,21556.48,Credit Card,Delivered,3.0
3,ORD00004,CUST043,PROD024,2024-01-06,Bangalore,Toys,5,41356.58,0.05,196443.76,Credit Card,Delivered,5.0
4,ORD00005,CUST008,PROD009,2024-01-08,Hyderabad,Furniture,5,16137.47,0.20,64549.88,Net Banking,Pending,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,ORD00196,CUST037,PROD030,2024-12-23,Pune,Furniture,4,23802.29,0.00,95209.16,Credit Card,Shipped,4.0
196,ORD00197,CUST033,PROD029,2024-12-25,Bangalore,Home & Kitchen,1,33443.38,0.20,26754.70,UPI,Delivered,4.0
197,ORD00198,CUST042,PROD014,2024-12-27,Delhi,Toys,5,8780.53,0.25,32926.99,UPI,Shipped,5.0
198,ORD00199,CUST044,PROD021,2024-12-29,Bangalore,Beauty,1,9774.99,0.15,8308.74,UPI,Shipped,5.0
199,ORD00200,CUST024,PROD006,2024-12-31,Delhi,Furniture,3,2234.26,0.25,5027.09,Net Banking,Shipped,4.0

In [61]:
bf.head(10).to_excel("new.xlsx",  index = False)
bf

,OrderID,CustomerID,ProductID,OrderDate,City,Category,Quantity,UnitPrice,Discount,TotalAmount,PaymentMode,Status,Rating
0,ORD00001,CUST039,PROD015,2024-01-01,Mumbai,Toys,3,5334.57,0.20,12802.97,Debit Card,Delivered,5.0
1,ORD00002,CUST029,PROD027,2024-01-02,Hyderabad,Electronics,4,45146.13,0.05,171555.29,Net Banking,Cancelled,3.0
2,ORD00003,CUST015,PROD022,2024-01-04,Hyderabad,Beauty,1,25360.57,0.15,21556.48,Credit Card,Delivered,3.0
3,ORD00004,CUST043,PROD024,2024-01-06,Bangalore,Toys,5,41356.58,0.05,196443.76,Credit Card,Delivered,5.0
4,ORD00005,CUST008,PROD009,2024-01-08,Hyderabad,Furniture,5,16137.47,0.20,64549.88,Net Banking,Pending,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,ORD00196,CUST037,PROD030,2024-12-23,Pune,Furniture,4,23802.29,0.00,95209.16,Credit Card,Shipped,4.0
196,ORD00197,CUST033,PROD029,2024-12-25,Bangalore,Home & Kitchen,1,33443.38,0.20,26754.70,UPI,Delivered,4.0
197,ORD00198,CUST042,PROD014,2024-12-27,Delhi,Toys,5,8780.53,0.25,32926.99,UPI,Shipped,5.0
198,ORD00199,CUST044,PROD021,2024-12-29,Bangalore,Beauty,1,9774.99,0.15,8308.74,UPI,Shipped,5.0
199,ORD00200,CUST024,PROD006,2024-12-31,Delhi,Furniture,3,2234.26,0.25,5027.09,Net Banking,Shipped,4.0

In [65]:
bf[bf['Rating']>3].to_excel("new.xlsx",  index = False)

In [8]:
import os
import pandas as pd

 
os.chdir(r"C:\Users\RAHUL N MURTHY\Downloads")


cf = pd.read_excel("missing_data_practice.xlsx")

print(df.head())

            Name   Age  Gender  Math  Science  English  Attendance       City  \
StudentID
S001       Rahul  20.0    Male  85.0     78.0      NaN        95.0      Delhi
S002       Priya   NaN  Female  90.0      NaN     85.0        88.0     Mumbai
S003        Amit  22.0     NaN   NaN     82.0     79.0         NaN  Bangalore
S004       Sneha  21.0  Female  78.0      NaN     92.0        92.0        NaN
S005       Vikas   NaN    Male  92.0     88.0      NaN        78.0    Chennai

          Grade
StudentID
S001          A
S002        NaN
S003          B
S004          A
S005         A+

In [7]:
df.set_index('StudentID' , inplace = True )
df

,Name,Age,Gender,Math,Science,English,Attendance,City,Grade
StudentID,,,,,,,,,
S001,Rahul,20.0,Male,85.0,78.0,NaN,95.0,Delhi,A
S002,Priya,NaN,Female,90.0,NaN,85.0,88.0,Mumbai,NaN
S003,Amit,22.0,NaN,NaN,82.0,79.0,NaN,Bangalore,B
S004,Sneha,21.0,Female,78.0,NaN,92.0,92.0,NaN,A
S005,Vikas,NaN,Male,92.0,88.0,NaN,78.0,Chennai,A+
S006,Pooja,23.0,NaN,65.0,70.0,68.0,NaN,Delhi,NaN
S007,Arjun,20.0,Male,NaN,91.0,87.0,85.0,NaN,B+
S008,Meera,NaN,Female,88.0,76.0,NaN,90.0,Mumbai,A
S009,Kiran,22.0,Male,72.0,NaN,80.0,NaN,Pune,NaN
S010,Suresh,21.0,NaN,95.0,85.0,90.0,96.0,NaN,A+

In [10]:
new_df = df.fillna(0)
new_df

,Name,Age,Gender,Math,Science,English,Attendance,City,Grade
StudentID,,,,,,,,,
S001,Rahul,20.0,Male,85.0,78.0,0.0,95.0,Delhi,A
S002,Priya,0.0,Female,90.0,0.0,85.0,88.0,Mumbai,0
S003,Amit,22.0,0,0.0,82.0,79.0,0.0,Bangalore,B
S004,Sneha,21.0,Female,78.0,0.0,92.0,92.0,0,A
S005,Vikas,0.0,Male,92.0,88.0,0.0,78.0,Chennai,A+
S006,Pooja,23.0,0,65.0,70.0,68.0,0.0,Delhi,0
S007,Arjun,20.0,Male,0.0,91.0,87.0,85.0,0,B+
S008,Meera,0.0,Female,88.0,76.0,0.0,90.0,Mumbai,A
S009,Kiran,22.0,Male,72.0,0.0,80.0,0.0,Pune,0
S010,Suresh,21.0,0,95.0,85.0,90.0,96.0,0,A+

In [11]:
new_df = df.fillna({"Gender" : "none" , "Science":0, "English": 0 ,  "Attendance": 0 , "City": "none"})
new_df

,Name,Age,Gender,Math,Science,English,Attendance,City,Grade
StudentID,,,,,,,,,
S001,Rahul,20.0,Male,85.0,78.0,0.0,95.0,Delhi,A
S002,Priya,NaN,Female,90.0,0.0,85.0,88.0,Mumbai,NaN
S003,Amit,22.0,none,NaN,82.0,79.0,0.0,Bangalore,B
S004,Sneha,21.0,Female,78.0,0.0,92.0,92.0,none,A
S005,Vikas,NaN,Male,92.0,88.0,0.0,78.0,Chennai,A+
S006,Pooja,23.0,none,65.0,70.0,68.0,0.0,Delhi,NaN
S007,Arjun,20.0,Male,NaN,91.0,87.0,85.0,none,B+
S008,Meera,NaN,Female,88.0,76.0,0.0,90.0,Mumbai,A
S009,Kiran,22.0,Male,72.0,0.0,80.0,0.0,Pune,NaN
S010,Suresh,21.0,none,95.0,85.0,90.0,96.0,none,A+

In [15]:
new_df =df.ffill()
new_df

,Name,Age,Gender,Math,Science,English,Attendance,City,Grade
StudentID,,,,,,,,,
S001,Rahul,20.0,Male,85.0,78.0,NaN,95.0,Delhi,A
S002,Priya,20.0,Female,90.0,78.0,85.0,88.0,Mumbai,A
S003,Amit,22.0,Female,90.0,82.0,79.0,88.0,Bangalore,B
S004,Sneha,21.0,Female,78.0,82.0,92.0,92.0,Bangalore,A
S005,Vikas,21.0,Male,92.0,88.0,92.0,78.0,Chennai,A+
S006,Pooja,23.0,Male,65.0,70.0,68.0,78.0,Delhi,A+
S007,Arjun,20.0,Male,65.0,91.0,87.0,85.0,Delhi,B+
S008,Meera,20.0,Female,88.0,76.0,87.0,90.0,Mumbai,A
S009,Kiran,22.0,Male,72.0,76.0,80.0,90.0,Pune,A
S010,Suresh,21.0,Male,95.0,85.0,90.0,96.0,Pune,A+

In [16]:
new_df = df.bfill()
new_df

,Name,Age,Gender,Math,Science,English,Attendance,City,Grade
StudentID,,,,,,,,,
S001,Rahul,20.0,Male,85.0,78.0,85.0,95.0,Delhi,A
S002,Priya,22.0,Female,90.0,82.0,85.0,88.0,Mumbai,B
S003,Amit,22.0,Female,78.0,82.0,79.0,92.0,Bangalore,B
S004,Sneha,21.0,Female,78.0,88.0,92.0,92.0,Chennai,A
S005,Vikas,23.0,Male,92.0,88.0,68.0,78.0,Chennai,A+
S006,Pooja,23.0,Male,65.0,70.0,68.0,85.0,Delhi,B+
S007,Arjun,20.0,Male,88.0,91.0,87.0,85.0,Mumbai,B+
S008,Meera,22.0,Female,88.0,76.0,80.0,90.0,Mumbai,A
S009,Kiran,22.0,Male,72.0,85.0,80.0,96.0,Pune,A+
S010,Suresh,21.0,NaN,95.0,85.0,90.0,96.0,NaN,A+

In [25]:
df_cleaned = df.dropna(how="any")
print(df_cleaned)

Empty DataFrame
Columns: [Name, Age, Gender, Math, Science, English, Attendance, City, Grade]
Index: []

In [27]:
df_cleaned = df.dropna(thresh = 2)
print(df_cleaned)

Empty DataFrame
Columns: [Name, Age, Gender, Math, Science, English, Attendance, City, Grade]
Index: []

In [28]:
os.chdir(r"C:\Users\RAHUL N MURTHY\Downloads")

all_sheets = pd.read_excel("missing_data_advanced.xlsx", sheet_name=None)